import type { Metadata } from "next";
import { headers } from "next/headers";
import { Inter, Geist_Mono } from "next/font/google";
import { SiteFooter } from "@/components/SiteFooter";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const hdrs = await headers();
  const hideFooterForPaperPunterRootRewrite =
    hdrs.get("x-paperpunter-root-rewrite") === "1";

  return (
    <html lang="en">
      <body
        className={`${inter.className} ${geistMono.variable} antialiased dark:bg-black min-h-screen flex flex-col`}
      >
        <main className="flex-1 bg-[#EEF6FB]">
          <div className="mx-auto max-w-6xl px-6 sm:px-8 lg:px-12 xl:px-16">
            {children}
          </div>
        </main>
        {hideFooterForPaperPunterRootRewrite ? null : <SiteFooter />}
      </body>
    </html>
  );
}
