import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${geistMono.variable} antialiased dark:bg-black`}
      >
        <div className="min-h-screen bg-[#EEF6FB]">
          <main className="mx-auto max-w-6xl px-6 sm:px-8 lg:px-12 xl:px-16">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
