import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${geistMono.variable} antialiased dark:bg-black min-h-screen flex flex-col`}
      >
        <main className="flex-1 bg-[#EEF6FB]">
          <div className="mx-auto max-w-6xl px-6 sm:px-8 lg:px-12 xl:px-16">
            {children}
          </div>
        </main>
        <footer className="border-t border-slate-200 py-3 px-4 text-center text-sm font-medium text-slate-700">
          <span className="font-semibold">Disclaimer:</span> Unofficial picks tool built for a private competition. Not affiliated with ANZ, Super Rugby, SANZAAR, or any teams.
        </footer>
      </body>
    </html>
  );
}
